version: '3.9'
services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - '4566-4597:4566-4597'
    environment:
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=localstack
      - AWS_SECRET_ACCESS_KEY=localstack
    volumes:
      - ./developer/localstack:/etc/localstack/init/ready.d/
      - ./data/localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  sqs-admin:
    container_name: sqs-admin
    image: pacovk/sqs-admin
    ports:
      - "3999:3999"
    environment:
      - SQS_AWS_REGION=us-east-1
      - SQS_ENDPOINT_URL=http://localstack:4566
    depends_on:
      - localstack

  importer-api:
    container_name: importer-api
    build:
      context: importer-api
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - ./importer-api/.env
    volumes:
      - ./importer-api/src:/opt/app/src
    ports:
      - 8000:8000
    depends_on:
      - localstack

  db:
    container_name: db
    image: postgres:16.1-alpine
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./developer/postgres:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    env_file:
      - ./worker/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U userinterest"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data

  worker:
    container_name: worker
    build:
      context: worker
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./worker/src:/opt/app/src
    env_file:
      - ./worker/.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      localstack:
        condition: service_healthy
    links:
      - db
      - redis
      - localstack