version: '3.9'
services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - '4566-4597:4566-4597'
    environment:
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=localstack
      - AWS_SECRET_ACCESS_KEY=localstack
    volumes:
      - ./developer/localstack:/etc/localstack/init/ready.d/
      - ./data/localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  sqs-admin:
    container_name: sqs-admin
    image: pacovk/sqs-admin
    ports:
      - "3999:3999"
    environment:
      - SQS_AWS_REGION=us-east-1
      - SQS_ENDPOINT_URL=http://localstack:4566
    depends_on:
      localstack:
        condition: service_healthy

  importer-api:
    container_name: importer-api
    build:
      context: importer-api
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - ./importer-api/.env
    volumes:
      - ./importer-api/src:/opt/app/src
    ports:
      - 8000:8000
    depends_on:
      localstack:
        condition: service_healthy

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data

  billing-worker:
    container_name: billing-worker
    build:
      context: billing-worker
      dockerfile: ./Dockerfile
    ports:
      - 8001:8001
    volumes:
      - ./billing-worker/src:/opt/app/src
    env_file:
      - ./billing-worker/.env
    depends_on:
      localstack:
        condition: service_healthy

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./developer/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - billing-worker

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/exported_dashboard.json
    volumes:
      - ./developer/grafana/provisioning:/etc/grafana/provisioning
      - ./developer/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
